#!/bin/sh
#BSUB -J g4_bench_norm
#BSUB -o g4_bench_norm_%J.out
#BSUB -e g4_bench_norm_%J.err
#BSUB -q hpcintrogpu
#BSUB -n 32
#BSUB -N
#BSUB -R "span[hosts=1]" 
#BSUB -gpu "num=2:mode=exclusive_process" 
#BSUB -W 10
#BSUB -R "rusage[mem=2048]" 

module load /appl9/nvhpc/2023_2311/modulefiles/nvhpc-nompi/23.11

RESOLUTION="100 150 200 250 300 350 400"

THREADS="24"

ITERATIONS="5000"


for R in $RESOLUTION
do
./poisson $R 5000 0.005 0.0 0 5
done 
